### ISSUE TITLE
Reboot with ESP32

### ISSUE THREAD

**Issue by Skysurfer-14** [LaCocoRoco/DataVisualizer#2]
The defaultExample.ino works perfect with Arduino UNO, but the same code on ESP32 DEVKIT V1 reboots every few seconds:

`Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400ec4fb  PS      : 0x00060130  A0      : 0x800d20b7  A1      : 0x3ffb1de0  
A2      : 0x0000001d  A3      : 0x3ffb1e22  A4      : 0x0000001d  A5      : 0x00000000  
A6      : 0x00000001  A7      : 0xff000000  A8      : 0x3ffb1e3e  A9      : 0x00000000  
A10     : 0x000000ff  A11     : 0xffffffff  A12     : 0x3ffb1df6  A13     : 0x00000001  
A14     : 0x3ffb1e22  A15     : 0x00000001  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffc  

Backtrace: 0x400ec4fb:0x3ffb1de0 0x400d20b4:0x3ffb1e00 0x400d12ee:0x3ffb1f40 0x400d0dc6:0x3ffb1f60 0x400d3a01:0x3ffb1fb0 0x40088a59:0x3ffb1fd0
Rebooting...
 #{:< 3 {Hd412 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
`

**Comment by LaCocoRoco** [comment]
I primarly developed and tested the library on UNO, MEGA and M0Pro (Zero).
The target was basically to support Atmel 8Bit and 32Bit Processors
I never intended to use the library on an ESP32.
In this respect there probably will never be a fix for this problem. I am sorry for the situation.
I will try to add a node or exclusion in future use related to this board.
